#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#


xrandr -s 0

xrdb -merge $HOME/.Xdefaults
xrdb -merge .Xresources
xsetroot -cursor_name left_ptr
xsetroot -solid '#0f0f0f'

xset b off
xset s off
xset -dpms

#xmodmap -e "keysym Super_R = SunCompose"

fbsetbg -b -solid "#0f0f0f"
nitrogen --restore &
numlockx on
xcompmgr -c -t-5 -l-5 -r4.2 -o.25 &
#{ sleep 1; urxvt -name ncmpcpp-clock -e ncmpcpp; } &
#chromium-browser &
#gmpc &
clementine &
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet &
fi
klipper &
kmix &
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export MPD_HOST=localhost
export MPD_PORT=6600
export OOO_FORCE_DESKTOP=gnome

# Use synapse as our app launcher. (-s: don't display until requested) 
#if [ -z "$(pgrep plasma-desktop)" ] ; then
#    plasma-desktop &
#fi

if [ -z "$(pgrep yakuake)" ] ; then
    yakuake &
fi
# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

# export SSH_ASKPASS="/usr/bin/ssh-askpass"
# cat /dev/null | ssh-add &

# I disable the middle mouse button because otherwise I constantly 
# accidentally paste unwanted text in the middle of my code while scrolling. 
# Note that the id of the mouse device may be different depending on 
# which usb port it is plugged into! To find it, use:
# xinput list |grep 'id='
# In the following command, the id is the first argument, the rest is 
# the remapping.

# Commented by default as it is assumed many users will not want this.
# xinput set-button-map 10 1 0 3 4 5 6 7

